import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        syntax: {
          property: "var(--syntax-property)",
          string: "var(--syntax-string)",
          number: "var(--syntax-number)",
          boolean: "var(--syntax-boolean)",
          tag: "var(--syntax-tag)",
          attribute: "var(--syntax-attribute)",
        },
        purr: {
          base: "var(--purr-base)",
          codefield: "var(--purr-code-bg)",
          surface: "var(--purr-surface)",
          elevated: "var(--purr-elevated)",
          overlay: "var(--purr-overlay)",
          highlight: "var(--purr-highlight)",
          muted: "var(--purr-muted)",
        },
        border: {
          subtle: "var(--border-subtle)",
          DEFAULT: "var(--border-default)",
          focus: "var(--border-focus)",
        },
        content: {
          primary: "var(--content-primary)",
          secondary: "var(--content-secondary)",
          tertiary: "var(--content-tertiary)",
          quaternary: "var(--content-quaternary)",
        },
        action: {
          emerald: {
            DEFAULT: "var(--action-emerald)",
            hover: "var(--action-emerald-hover)",
            surface: "var(--action-emerald-surface)",
            border: "var(--action-emerald-border)",
          },
          graphql: {
            DEFAULT: "var(--action-graphql)",
            hover: "var(--action-graphql-hover)",
            surface: "var(--action-graphql-surface)",
            border: "var(--action-graphql-border)",
          },
          brand: {
            DEFAULT: "var(--action-brand)",
            hover: "var(--action-brand-hover)",
            surface: "var(--action-brand-surface)",
            border: "var(--action-brand-border)",
          },
        },
        accent: {
          emerald: "var(--accent-emerald)",
          blue: "var(--accent-blue)",
          orange: "var(--accent-orange)",
          violet: "var(--accent-violet)",
          red: "var(--accent-red)",
          cyan: "var(--accent-cyan)",
          slate: "var(--accent-slate)",
          magenta: "var(--accent-magenta)",
        },
        method: {
          get: "var(--method-get)",
          post: "var(--method-post)",
          put: "var(--method-put)",
          patch: "var(--method-patch)",
          delete: "var(--method-delete)",
          head: "var(--method-head)",
          options: "var(--method-options)",
        },
        status: {
          success: "var(--status-success)",
          redirect: "var(--status-redirect)",
          "client-error": "var(--status-client-error)",
          "server-error": "var(--status-server-error)",
        },
        mac: {
          close: "var(--mac-close)",
          minimize: "var(--mac-minimize)",
          maximize: "var(--mac-maximize)",
        },
      },
      spacing: {
        "ui-0": "var(--space-0)",
        "ui-1": "var(--space-1)",
        "ui-1-5": "var(--space-1-5)",
        "ui-2": "var(--space-2)",
        "ui-2-5": "var(--space-2-5)",
        "ui-3": "var(--space-3)",
        "ui-3-5": "var(--space-3-5)",
        "ui-4": "var(--space-4)",
        "ui-5": "var(--space-5)",
        "ui-6": "var(--space-6)",
        "ui-7": "var(--space-7)",
        "ui-8": "var(--space-8)",
        "ui-10": "var(--space-10)",
        "ui-12": "var(--space-12)",
        "ui-16": "var(--space-16)",
        "control-xs": "var(--control-height-xs)",
        "control-sm": "var(--control-height-sm)",
        "control-md": "var(--control-height-md)",
        "control-lg": "var(--control-height-lg)",
        panel: "var(--panel-min-height)",
        content: "var(--content-max-width)",
        "method-popover": "var(--method-popover-width)",
        "auth-grant": "var(--auth-grant-width)",
      },
      maxWidth: {
        "validation-popover": "var(--validation-popover-width)",
      },
      borderRadius: {
        DEFAULT: "var(--radius-md)",
        "ui-sm": "var(--radius-sm)",
        "ui-md": "var(--radius-md)",
        "ui-lg": "var(--radius-lg)",
        "ui-xl": "var(--radius-xl)",
      },
      borderWidth: {
        DEFAULT: "var(--border-width-hairline)",
        hairline: "var(--border-width-hairline)",
        emphasis: "var(--border-width-emphasis)",
      },
      boxShadow: {
        panel: "var(--shadow-panel)",
        popover: "var(--shadow-popover)",
        button: "var(--shadow-button)",
        action: "var(--shadow-action)",
      },
      fontFamily: {
        ui: ["Space Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        code: ["Google Sans Code", "ui-monospace", "monospace"],
        sans: ["Space Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["Google Sans Code", "ui-monospace", "monospace"],
      },
      fontSize: {
        "ui-2xs": [
          "var(--font-size-2xs)",
          { lineHeight: "var(--line-height-2xs)" },
        ],
        "ui-xs": [
          "var(--font-size-xs)",
          { lineHeight: "var(--line-height-xs)" },
        ],
        "ui-sm": [
          "var(--font-size-sm)",
          { lineHeight: "var(--line-height-sm)" },
        ],
        "ui-md": [
          "var(--font-size-md)",
          { lineHeight: "var(--line-height-md)" },
        ],
        "ui-lg": [
          "var(--font-size-lg)",
          { lineHeight: "var(--line-height-lg)" },
        ],
        "ui-xl": [
          "var(--font-size-xl)",
          { lineHeight: "var(--line-height-xl)" },
        ],
      },
      fontWeight: {
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
      },
      transitionDuration: {
        "ui-fast": "var(--duration-fast)",
        "ui-normal": "var(--duration-normal)",
      },
      transitionProperty: {
        "ui-expand": "grid-template-rows, opacity",
      },
      gridTemplateRows: {
        "ui-collapsed": "0fr",
        "ui-expanded": "1fr",
      },
      opacity: {
        "ui-hidden": "var(--opacity-hidden)",
        "ui-disabled": "var(--opacity-disabled)",
        "ui-inactive": "var(--opacity-inactive)",
        "ui-visible": "var(--opacity-visible)",
      },
    },
  },
  plugins: [],
} satisfies Config;
